#spring:
#  application:
#    name: trace-2
server:
  port: 8781
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  sleuth:
    sampler:
      probability: 1  #采样频率
    web:
      enabled: true
    zipkin:
      base-url: http://localhost:9411/  #zipkin服务地址
