eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8784
spring:
  application:
    name: service-gateway
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #开启小写验证，默认feign根据服务名查找都是用的全大写
      routes:
        # 2. 路由
#        - id: service-ribbon
#          uri: lb://service-ribbon
#          predicates:
#            - Path=/ribbon/**
#          filters:
#            - StripPrefix=1 # 去除掉前面1个前缀之后
        #限流
        - id: limit_route
          uri: https://www.baidu.com/
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
        # 1.qucik start
#        - id: path-route
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/baidu/**
#          filters:
#            - StripPrefix=1

