eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8784
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #开启小写验证，默认feign根据服务名查找都是用的全大写
      routes:
        - id: service-ribbon
          uri: lb://service-ribbon
          predicates:
            - Path=/ribbon/**
          filters:
            - StripPrefix=1 # 去除掉前面1个前缀之后
        # 1.qucik start
#        - id: path-route
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/baidu/**
#          filters:
#            - StripPrefix=1

