eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
