#此段配置移动至 bootstrap.properties 中
#spring:
#  application:
#    name: trace-1
server:
  port: 8780
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  sleuth:
    sampler:
      probability: 1  #采样频率
    web:
      enabled: true
    zipkin:
      base-url: http://localhost:9411/  #zipkin服务地址
